TRAINED_MODEL_MODEL1_FILENAME = 'model1.pt'
TRAINED_MODEL_MODEL2_FILENAME = 'model2.hf'
TRAINED_MODEL_GCS_BUCKET = 'pirelly-assets'
TRAINED_MODEL_GCS_PATH_MODEL1 = 'AI-trained-models/BGR/' + TRAINED_MODEL_MODEL1_FILENAME
TRAINED_MODEL_GCS_PATH_MODEL2 = 'AI-trained-models/HSE/' + TRAINED_MODEL_MODEL2_FILENAME
TRAINED_MODEL_LOCAL_PATH = '/tmp/models/'
LOCAL_INPUT_PATH = '/tmp/input'
LOCAL_OUTPUT_PATH = '/tmp/output'